apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: {{ .Values.movieDb.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.movieDb.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.movieDb.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.movieDb.database | quote }}
          volumeMounts:
            - name: movie-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: movie-db-storage
          persistentVolumeClaim:
            claimName: movie-db-pvc