apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service

  template:
    metadata:
      labels:
        app: cast-service

    spec:
      containers:
        - name: cast-service
          image: nimamrze/cast-service:{{ .Values.image.tag }}

          command: ["uvicorn"]

          args:
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            - --loop
            - asyncio

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev