---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - args:
            - app.main:app
            - '--host'
            - 0.0.0.0
            - '--port'
            - '8000'
            - '--loop'
            - asyncio
          command: ["uvicorn"]
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
            - name: CAST_SERVICE_HOST_URL
              value: http://cast-service:8000/api/v1/casts/
          image: nimamrze/movie-service:{{ .Values.image.tag }}
          name: movie-service
          ports:
            - containerPort: 8000