apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: movie_db_username
            - name: POSTGRES_PASSWORD
              value: movie_db_password
            - name: POSTGRES_DB
              value: movie_db_dev
          volumeMounts:
            - name: movie-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: movie-db-storage
          persistentVolumeClaim:
            claimName: movie-db-pvc
