replicaCount: 1

image:
  tag: v1
  pullPolicy: IfNotPresent

movieService:
  image: nimamrze/movie-service
  port: 8000
  databaseUri: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
  castServiceUrl: http://cast-service:8000/api/v1/casts/

castService:
  image: nimamrze/cast-service
  port: 8000
  databaseUri: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev

movieDb:
  image: postgres:12.1-alpine
  username: movie_db_username
  password: movie_db_password
  database: movie_db_dev
  storage: 1Gi

castDb:
  image: postgres:12.1-alpine
  username: cast_db_username
  password: cast_db_password
  database: cast_db_dev
  storage: 1Gi

nginx:
  image: nginx:latest
  port: 8080
  serviceType: ClusterIP

ingress:
  enabled: true
  className: traefik
  host: movie-dev.services-cloud.abrdns.com